# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Theme Settings
#
# Review documentation to determine if you should use `theme` or `remote_theme`
# https://mmistakes.github.io/minimal-mistakes/docs/quick-start-guide/#installing-the-theme

# theme                  : "minimal-mistakes-jekyll"
# remote_theme           : "mmistakes/minimal-mistakes"
minimal_mistakes_skin    : "default" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "en-US"
title                    : "ORDLIKE"
title_separator          : "|"
subtitle                 : "Today is better than yesterday"
name                     : "Chae-Hwan Park"
description              : "Welcome to ordlike world!"
url                      : "https://ordlike.github.io"
baseurl                  : #"/main"
repository               : # GitHub username/repo-name e.g. "mmistakes/minimal-mistakes"
teaser                   : # path of fallback teaser image, e.g. "/assets/images/500x300.png"
logo                     : "/images/new_logo4.png"
masthead_title           : # overrides the website title displayed in the masthead, use " " for no title
#breadcrumbs            : false # true, false (default)
words_per_minute         : 200

comments:
  provider               : "disqus" # false (default), "disqus", "discourse", "facebook", "staticman", "staticman_v2", "utterances", "giscus", "custom"
  disqus:
    shortname            : "ordlike"
  discourse:
    server               :
  facebook:
    appid                :
    num_posts            :
    colorscheme          :
  utterances:
    theme                :
    issue_term           :
  giscus:
    repo_id              :
    category_name        :
    category_id          :
    discussion_term      :
    reactions_enabled    :
    theme                :
  staticman:
    branch               :
    endpoint             :

reCaptcha:
  siteKey                :
  secret                 :

atom_feed:
  path                   :
  hide                   :

search                   :
search_full_content      :
search_provider          :

lunr:
  search_within_pages    :

algolia:
  application_id         :
  index_name             :
  search_only_api_key    :
  powered_by             :

google:
  search_engine_id       :
  instant_search         :

# SEO Related
google_site_verification :
bing_site_verification   :
naver_site_verification  :
yandex_site_verification :
baidu_site_verification  :

# Social Sharing
twitter:
  username               :

facebook:
  username               :
  app_id                 :
  publisher              :

og_image                 :

# For specifying social profiles
social:
  type                   : Person
  name                   : "Chae-Hwan Park"
  links:
    - "https://orcid.org/0009-0009-4607-7920"
    - "https://github.com/ordlike"
    - "https://www.linkedin.com/in/chae-hwan-park-00977531a"
    - "https://blog.naver.com/ordlike"
    - "https://instagram.com/chae_wanny?igshid=ZDc4ODBmNjlmNQ=="

# Analytics
analytics:
  provider               : "google-gtag"
  google:
    tracking_id          : "G-VVZCE46RNQ"
    anonymize_ip         : false

# Site Author
author:
  name             : "Chae-Hwan Park"
  avatar           : "./../assets/new_images/profile.jpg"
  bio              : "3rd year, **SNU Tech M.S.-Ph.D** <br> **Hanyang Tech B.S.**"
  location         : "South Korea"
  email            :
  links:
    - label: "ordlike@snu.ac.kr"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:ordlike@snu.ac.kr"

    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0009-0009-4607-7920"

    - label: "Blog"
      icon: "fas fa-fw fa-link"
      url: "https://blog.naver.com/ordlike"

    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ordlike"

    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/chae_wanny?igshid=ZDc4ODBmNjlmNQ=="

    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/chae-hwan-park-00977531a"

# Site Footer
footer:
  links:
    - label: "Blog"
      icon: "fas fa-fw fa-link"
      url: "https://blog.naver.com/ordlike"

    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ordlike"

    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/chae-hwan-park-00977531a"

    - label: "ORCID"
      icon: "fab fa-fw fa-orcid"
      url: "https://orcid.org/0009-0009-4607-7920"

    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/chae_wanny?igshid=ZDc4ODBmNjlmNQ=="

# Reading Files
include:
  - .htaccess
  - _pages

exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
  - /docs
  - /test

keep_files:
  - .git
  - .svn

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone:

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# Archives
category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/